export const styles = {
  root: {
    background: "#0c0e13",
    color: "#dde3f0",
    fontFamily: "'Sora', sans-serif",
    minHeight: "100vh",
    padding: "48px 24px",
    fontSize: 14,
    lineHeight: 1.6,
  },
  page: {
    maxWidth: 780,
    margin: "0 auto",
  },
  header: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 24,
    alignItems: "start",
    paddingBottom: 36,
    borderBottom: "1px solid #1e2330",
    marginBottom: 36,
  },
  name: {
    fontSize: 36,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    color: "#fff",
  },
  nameAccent: { color: "#4f8ef7" },
  titleMono: {
    fontFamily: "'DM Mono', monospace",
    fontSize: 12,
    color: "#6b7694",
    marginTop: 8,
    letterSpacing: "0.05em",
  },
  contacts: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-end",
    paddingTop: 4,
  },
  contactItem: {
    fontFamily: "'DM Mono', monospace",
    fontSize: 12,
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    gap: 6,
    transition: "color 0.2s",
    cursor: "pointer",
  },
  dot: (color) => ({
    width: 5,
    height: 5,
    borderRadius: "50%",
    background: color,
    flexShrink: 0,
  }),
  section: {
    marginBottom: 36,
  },
  sectionLabel: {
    fontFamily: "'DM Mono', monospace",
    fontSize: 10,
    letterSpacing: "0.15em",
    color: "#4f8ef7",
    textTransform: "uppercase",
    marginBottom: 16,
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    background: "#1e2330",
  },
  aboutText: {
    color: "#dde3f0",
    fontWeight: 300,
    maxWidth: 620,
    lineHeight: 1.75,
  },
  stackGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 12,
  },
  stackGroup: {
    background: "#13161e",
    border: "1px solid #1e2330",
    borderRadius: 8,
    padding: "14px 16px",
  },
  stackGroupTitle: (color) => ({
    fontFamily: "'DM Mono', monospace",
    fontSize: 10,
    color,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    marginBottom: 10,
  }),
  tags: { display: "flex", flexWrap: "wrap", gap: 6 },
  tag: {
    background: "#161c2d",
    border: "1px solid #1e2330",
    borderRadius: 4,
    padding: "3px 8px",
    fontFamily: "'DM Mono', monospace",
    fontSize: 11,
    color: "#dde3f0",
  },
  projectsList: { display: "flex", flexDirection: "column", gap: 12 },
  projectCard: (hovered) => ({
    background: "#13161e",
    border: `1px solid ${hovered ? "#4f8ef7" : "#1e2330"}`,
    borderRadius: 10,
    padding: "18px 20px",
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 12,
    alignItems: "start",
    transition: "border-color 0.2s, transform 0.2s",
    transform: hovered ? "translateX(4px)" : "none",
    cursor: "default",
  }),
  projectName: {
    fontWeight: 600,
    fontSize: 15,
    color: "#fff",
    marginBottom: 4,
  },
  projectDesc: {
    fontSize: 13,
    color: "#6b7694",
    lineHeight: 1.55,
    marginBottom: 10,
  },
  projectBadge: {
    fontFamily: "'DM Mono', monospace",
    fontSize: 10,
    color: "#4f8ef7",
    background: "rgba(79,142,247,0.08)",
    border: "1px solid rgba(79,142,247,0.2)",
    borderRadius: 4,
    padding: "3px 8px",
    whiteSpace: "nowrap",
  },
  skillsCols: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px 32px",
  },
  skillLine: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "#dde3f0",
    padding: "6px 0",
    borderBottom: "1px solid #1e2330",
  },
  arrow: {
    color: "#4f8ef7",
    fontFamily: "'DM Mono', monospace",
    fontSize: 11,
    flexShrink: 0,
  },
  footer: {
    fontFamily: "'DM Mono', monospace",
    fontSize: 11,
    color: "#6b7694",
    textAlign: "center",
    paddingTop: 24,
    borderTop: "1px solid #1e2330",
    letterSpacing: "0.05em",
  },
};
